/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISunswapMigrator,
  ISunswapMigratorInterface,
} from "../../../contracts/interfaces/ISunswapMigrator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountTokenMin",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountETHMin",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISunswapMigrator__factory {
  static readonly abi = _abi;
  static createInterface(): ISunswapMigratorInterface {
    return new utils.Interface(_abi) as ISunswapMigratorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISunswapMigrator {
    return new Contract(address, _abi, signerOrProvider) as ISunswapMigrator;
  }
}
