/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v1 from "./V1";
export type { v1 };
export type { IERC20 } from "./IERC20";
export type { ISunSwapFactory } from "./ISunSwapFactory";
export type { ISunSwapPair } from "./ISunSwapPair";
export type { ISunswapMigrator } from "./ISunswapMigrator";
export type { ISunswapRouter01 } from "./ISunswapRouter01";
export type { ISunswapRouter02 } from "./ISunswapRouter02";
export type { IWETH } from "./IWETH";
