/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as factoryDeploySol from "./FactoryDeploy.sol";
export type { factoryDeploySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { SunSwapERC20 } from "./SunSwapERC20";
export type { SunSwapFactory } from "./SunSwapFactory";
export type { SunSwapPair } from "./SunSwapPair";
export * as factories from "./factories";
export type { FactoryAssembly } from "./FactoryDeploy.sol/FactoryAssembly";
export { FactoryAssembly__factory } from "./factories/FactoryDeploy.sol/FactoryAssembly__factory";
export type { IERC20 } from "./interfaces/IERC20";
export { IERC20__factory } from "./factories/interfaces/IERC20__factory";
export type { ISunSwapCallee } from "./interfaces/ISunSwapCallee";
export { ISunSwapCallee__factory } from "./factories/interfaces/ISunSwapCallee__factory";
export type { ISunSwapERC20 } from "./interfaces/ISunSwapERC20";
export { ISunSwapERC20__factory } from "./factories/interfaces/ISunSwapERC20__factory";
export type { ISunSwapFactory } from "./interfaces/ISunSwapFactory";
export { ISunSwapFactory__factory } from "./factories/interfaces/ISunSwapFactory__factory";
export type { ISunSwapPair } from "./interfaces/ISunSwapPair";
export { ISunSwapPair__factory } from "./factories/interfaces/ISunSwapPair__factory";
export { SunSwapERC20__factory } from "./factories/SunSwapERC20__factory";
export { SunSwapFactory__factory } from "./factories/SunSwapFactory__factory";
export { SunSwapPair__factory } from "./factories/SunSwapPair__factory";
export type { ERC20 } from "./test/ERC20";
export { ERC20__factory } from "./factories/test/ERC20__factory";
