/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { Multicall } from "./Multicall";
export type { SunswapMigrator } from "./SunswapMigrator";
export type { SunswapRouter01 } from "./SunswapRouter01";
export type { SunswapRouter02 } from "./SunswapRouter02";
