/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { ISunSwapCallee } from "./ISunSwapCallee";
export type { ISunSwapERC20 } from "./ISunSwapERC20";
export type { ISunSwapFactory } from "./ISunSwapFactory";
export type { ISunSwapPair } from "./ISunSwapPair";
